// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A Finding resource represents a vulnerability instance identified during a
/// ScanRun.
public struct Finding: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the Finding. The name follows the format of
  /// 'projects/{projectId}/scanConfigs/{scanConfigId}/scanruns/{scanRunId}/findings/{findingId}'.
  /// The finding IDs are generated by the system.
  public var name: Swift.String = Swift.String()

  /// Output only. The type of the Finding.
  /// Detailed and up-to-date information on findings can be found here:
  /// https://cloud.google.com/security-command-center/docs/how-to-remediate-web-security-scanner-findings
  public var findingType: Swift.String = Swift.String()

  /// Output only. The severity level of the reported vulnerability.
  public var severity: Finding.Severity = Finding.Severity()

  /// Output only. The http method of the request that triggered the vulnerability, in
  /// uppercase.
  public var httpMethod: Swift.String = Swift.String()

  /// Output only. The URL produced by the server-side fuzzer and used in the request that
  /// triggered the vulnerability.
  public var fuzzedUrl: Swift.String = Swift.String()

  /// Output only. The body of the request that triggered the vulnerability.
  public var body: Swift.String = Swift.String()

  /// Output only. The description of the vulnerability.
  public var description: Swift.String = Swift.String()

  /// Output only. The URL containing human-readable payload that user can leverage to
  /// reproduce the vulnerability.
  public var reproductionUrl: Swift.String = Swift.String()

  /// Output only. If the vulnerability was originated from nested IFrame, the immediate
  /// parent IFrame is reported.
  public var frameUrl: Swift.String = Swift.String()

  /// Output only. The URL where the browser lands when the vulnerability is detected.
  public var finalUrl: Swift.String = Swift.String()

  /// Output only. The tracking ID uniquely identifies a vulnerability instance across
  /// multiple ScanRuns.
  public var trackingId: Swift.String = Swift.String()

  /// Output only. An addon containing information reported for a vulnerability with an HTML
  /// form, if any.
  public var form: Form? = nil

  /// Output only. An addon containing information about outdated libraries.
  public var outdatedLibrary: OutdatedLibrary? = nil

  /// Output only. An addon containing detailed information regarding any resource causing the
  /// vulnerability such as JavaScript sources, image, audio files, etc.
  public var violatingResource: ViolatingResource? = nil

  /// Output only. An addon containing information about vulnerable or missing HTTP headers.
  public var vulnerableHeaders: VulnerableHeaders? = nil

  /// Output only. An addon containing information about request parameters which were found
  /// to be vulnerable.
  public var vulnerableParameters: VulnerableParameters? = nil

  /// Output only. An addon containing information reported for an XSS, if any.
  public var xss: Xss? = nil

  /// Output only. An addon containing information reported for an XXE, if any.
  public var xxe: Xxe? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Finding`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Finding().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let findingType = CodingKeys(stringValue: "findingType")
    static let severity = CodingKeys(stringValue: "severity")
    static let httpMethod = CodingKeys(stringValue: "httpMethod")
    static let fuzzedUrl = CodingKeys(stringValue: "fuzzedUrl")
    static let body = CodingKeys(stringValue: "body")
    static let description = CodingKeys(stringValue: "description")
    static let reproductionUrl = CodingKeys(stringValue: "reproductionUrl")
    static let frameUrl = CodingKeys(stringValue: "frameUrl")
    static let finalUrl = CodingKeys(stringValue: "finalUrl")
    static let trackingId = CodingKeys(stringValue: "trackingId")
    static let form = CodingKeys(stringValue: "form")
    static let outdatedLibrary = CodingKeys(stringValue: "outdatedLibrary")
    static let violatingResource = CodingKeys(stringValue: "violatingResource")
    static let vulnerableHeaders = CodingKeys(stringValue: "vulnerableHeaders")
    static let vulnerableParameters = CodingKeys(stringValue: "vulnerableParameters")
    static let xss = CodingKeys(stringValue: "xss")
    static let xxe = CodingKeys(stringValue: "xxe")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "findingType",
      "severity",
      "httpMethod",
      "fuzzedUrl",
      "body",
      "description",
      "reproductionUrl",
      "frameUrl",
      "finalUrl",
      "trackingId",
      "form",
      "outdatedLibrary",
      "violatingResource",
      "vulnerableHeaders",
      "vulnerableParameters",
      "xss",
      "xxe",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .findingType) {
      self.findingType = value
    }
    if let value = try container.decodeIfPresent(Finding.Severity.self, forKey: .severity) {
      self.severity = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .httpMethod) {
      self.httpMethod = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fuzzedUrl) {
      self.fuzzedUrl = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .body) {
      self.body = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .reproductionUrl) {
      self.reproductionUrl = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .frameUrl) {
      self.frameUrl = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .finalUrl) {
      self.finalUrl = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .trackingId) {
      self.trackingId = value
    }
    self.form = try container.decodeIfPresent(Form.self, forKey: .form)
    self.outdatedLibrary = try container.decodeIfPresent(
      OutdatedLibrary.self, forKey: .outdatedLibrary)
    self.violatingResource = try container.decodeIfPresent(
      ViolatingResource.self, forKey: .violatingResource)
    self.vulnerableHeaders = try container.decodeIfPresent(
      VulnerableHeaders.self, forKey: .vulnerableHeaders)
    self.vulnerableParameters = try container.decodeIfPresent(
      VulnerableParameters.self, forKey: .vulnerableParameters)
    self.xss = try container.decodeIfPresent(Xss.self, forKey: .xss)
    self.xxe = try container.decodeIfPresent(Xxe.self, forKey: .xxe)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.findingType, forKey: .findingType)
    try container.encode(self.severity, forKey: .severity)
    try container.encode(self.httpMethod, forKey: .httpMethod)
    try container.encode(self.fuzzedUrl, forKey: .fuzzedUrl)
    try container.encode(self.body, forKey: .body)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.reproductionUrl, forKey: .reproductionUrl)
    try container.encode(self.frameUrl, forKey: .frameUrl)
    try container.encode(self.finalUrl, forKey: .finalUrl)
    try container.encode(self.trackingId, forKey: .trackingId)
    try container.encodeIfPresent(self.form, forKey: .form)
    try container.encodeIfPresent(self.outdatedLibrary, forKey: .outdatedLibrary)
    try container.encodeIfPresent(self.violatingResource, forKey: .violatingResource)
    try container.encodeIfPresent(self.vulnerableHeaders, forKey: .vulnerableHeaders)
    try container.encodeIfPresent(self.vulnerableParameters, forKey: .vulnerableParameters)
    try container.encodeIfPresent(self.xss, forKey: .xss)
    try container.encodeIfPresent(self.xxe, forKey: .xxe)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The severity level of a vulnerability.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Severity: Codable, Equatable, Hashable, Sendable {
    /// No severity specified. The default value.
    case unspecified
    /// Critical severity.
    case critical
    /// High severity.
    case high
    /// Medium severity.
    case medium
    /// Low severity.
    case low
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .critical: return 1
      case .high: return 2
      case .medium: return 3
      case .low: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SEVERITY_UNSPECIFIED"
      case .critical: return "CRITICAL"
      case .high: return "HIGH"
      case .medium: return "MEDIUM"
      case .low: return "LOW"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Severity/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SEVERITY_UNSPECIFIED": self = .unspecified
      case "CRITICAL": self = .critical
      case "HIGH": self = .high
      case "MEDIUM": self = .medium
      case "LOW": self = .low
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Severity/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .critical
      case 2: self = .high
      case 3: self = .medium
      case 4: self = .low
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SEVERITY_UNSPECIFIED")
      case .critical: return try container.encode("CRITICAL")
      case .high: return try container.encode("HIGH")
      case .medium: return try container.encode("MEDIUM")
      case .low: return try container.encode("LOW")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.websecurityscanner.v1.Finding"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
