// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A ScanRunLog is an output-only proto used for Stackdriver customer logging.
/// It is used for logs covering the start and end of scan pipelines.
/// Other than an added summary, this is a subset of the ScanRun.
/// Representation in logs is either a proto Struct, or converted to JSON.
/// Next id: 9
public struct ScanRunLog: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Human friendly message about the event.
  public var summary: Swift.String = Swift.String()

  /// The resource name of the ScanRun being logged.
  public var name: Swift.String = Swift.String()

  /// The execution state of the ScanRun.
  public var executionState: ScanRun.ExecutionState = ScanRun.ExecutionState()

  /// The result state of the ScanRun.
  public var resultState: ScanRun.ResultState = ScanRun.ResultState()

  public var urlsCrawledCount: Swift.Int64 = Swift.Int64()

  public var urlsTestedCount: Swift.Int64 = Swift.Int64()

  public var hasFindings: Swift.Bool = Swift.Bool()

  public var errorTrace: ScanRunErrorTrace? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ScanRunLog`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ScanRunLog().with { $0.summary = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let summary = CodingKeys(stringValue: "summary")
    static let name = CodingKeys(stringValue: "name")
    static let executionState = CodingKeys(stringValue: "executionState")
    static let resultState = CodingKeys(stringValue: "resultState")
    static let urlsCrawledCount = CodingKeys(stringValue: "urlsCrawledCount")
    static let urlsTestedCount = CodingKeys(stringValue: "urlsTestedCount")
    static let hasFindings = CodingKeys(stringValue: "hasFindings")
    static let errorTrace = CodingKeys(stringValue: "errorTrace")

    static let _knownKeys: Set<Swift.String> = [
      "summary",
      "name",
      "executionState",
      "resultState",
      "urlsCrawledCount",
      "urlsTestedCount",
      "hasFindings",
      "errorTrace",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .summary) {
      self.summary = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(
      ScanRun.ExecutionState.self, forKey: .executionState)
    {
      self.executionState = value
    }
    if let value = try container.decodeIfPresent(ScanRun.ResultState.self, forKey: .resultState) {
      self.resultState = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .urlsCrawledCount) {
      self.urlsCrawledCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .urlsTestedCount) {
      self.urlsTestedCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .hasFindings) {
      self.hasFindings = value
    }
    self.errorTrace = try container.decodeIfPresent(ScanRunErrorTrace.self, forKey: .errorTrace)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.summary, forKey: .summary)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.executionState, forKey: .executionState)
    try container.encode(self.resultState, forKey: .resultState)
    try container.encode(self.urlsCrawledCount, forKey: .urlsCrawledCount)
    try container.encode(self.urlsTestedCount, forKey: .urlsTestedCount)
    try container.encode(self.hasFindings, forKey: .hasFindings)
    try container.encodeIfPresent(self.errorTrace, forKey: .errorTrace)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.websecurityscanner.v1.ScanRunLog"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
