// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A ScanConfig resource contains the configurations to launch a scan.
public struct ScanConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name of the ScanConfig. The name follows the format of
  /// 'projects/{projectId}/scanConfigs/{scanConfigId}'. The ScanConfig IDs are
  /// generated by the system.
  public var name: Swift.String = Swift.String()

  /// Required. The user provided display name of the ScanConfig.
  public var displayName: Swift.String = Swift.String()

  /// The maximum QPS during scanning. A valid value ranges from 5 to 20
  /// inclusively. If the field is unspecified or its value is set 0, server will
  /// default to 15. Other values outside of [5, 20] range will be rejected with
  /// INVALID_ARGUMENT error.
  public var maxQps: Swift.Int32 = Swift.Int32()

  /// Required. The starting URLs from which the scanner finds site pages.
  public var startingUrls: [Swift.String] = []

  /// The authentication configuration. If specified, service will use the
  /// authentication configuration during scanning.
  public var authentication: ScanConfig.Authentication? = nil

  /// The user agent used during scanning.
  public var userAgent: ScanConfig.UserAgent = ScanConfig.UserAgent()

  /// The excluded URL patterns as described in
  /// https://cloud.google.com/security-command-center/docs/how-to-use-web-security-scanner#excluding_urls
  public var blacklistPatterns: [Swift.String] = []

  /// The schedule of the ScanConfig.
  public var schedule: ScanConfig.Schedule? = nil

  /// Controls export of scan configurations and results to Security
  /// Command Center.
  public var exportToSecurityCommandCenter: ScanConfig.ExportToSecurityCommandCenter =
    ScanConfig.ExportToSecurityCommandCenter()

  /// The risk level selected for the scan
  public var riskLevel: ScanConfig.RiskLevel = ScanConfig.RiskLevel()

  /// Whether the scan config is managed by Web Security Scanner, output
  /// only.
  public var managedScan: Swift.Bool = Swift.Bool()

  /// Whether the scan configuration has enabled static IP address scan feature.
  /// If enabled, the scanner will access applications from static IP addresses.
  public var staticIpScan: Swift.Bool = Swift.Bool()

  /// Whether to keep scanning even if most requests return HTTP error codes.
  public var ignoreHttpStatusErrors: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `ScanConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ScanConfig().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Scan authentication configuration.
  public struct Authentication: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required.
    /// Authentication configuration
    public var authentication: OneOf_Authentication? = nil

    /// Initialize a new instance of `Authentication`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Authentication().with { $0.googleAccount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case googleAccount = "googleAccount"
      case customAccount = "customAccount"
      case iapCredential = "iapCredential"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var authentication: OneOf_Authentication? = nil
      let authenticationCheckAndSet = {
        if authentication != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'authentication'"))
        }
        authentication = $0
      }
      if let googleAccount = try container.decodeIfPresent(
        ScanConfig.Authentication.GoogleAccount?.self, forKey: .googleAccount)
      {
        try authenticationCheckAndSet(.googleAccount(googleAccount))
      }
      if let customAccount = try container.decodeIfPresent(
        ScanConfig.Authentication.CustomAccount?.self, forKey: .customAccount)
      {
        try authenticationCheckAndSet(.customAccount(customAccount))
      }
      if let iapCredential = try container.decodeIfPresent(
        ScanConfig.Authentication.IapCredential?.self, forKey: .iapCredential)
      {
        try authenticationCheckAndSet(.iapCredential(iapCredential))
      }
      self.authentication = authentication
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.authentication {
        switch choice {
        case .googleAccount(let value):
          try container.encode(value, forKey: .googleAccount)
        case .customAccount(let value):
          try container.encode(value, forKey: .customAccount)
        case .iapCredential(let value):
          try container.encode(value, forKey: .iapCredential)
        }
      }
    }

    /// Describes authentication configuration that uses a Google account.
    @available(*, deprecated)
    public struct GoogleAccount: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. The user name of the Google account.
      public var username: Swift.String = Swift.String()

      /// Required. Input only. The password of the Google account. The credential is stored encrypted
      /// and not returned in any response nor included in audit logs.
      public var password: Swift.String = Swift.String()

      /// Initialize a new instance of `GoogleAccount`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = GoogleAccount().with { $0.username = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.websecurityscanner.v1.ScanConfig.Authentication.GoogleAccount"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Describes authentication configuration that uses a custom account.
    public struct CustomAccount: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. The user name of the custom account.
      public var username: Swift.String = Swift.String()

      /// Required. Input only. The password of the custom account. The credential is stored encrypted
      /// and not returned in any response nor included in audit logs.
      public var password: Swift.String = Swift.String()

      /// Required. The login form URL of the website.
      public var loginUrl: Swift.String = Swift.String()

      /// Initialize a new instance of `CustomAccount`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = CustomAccount().with { $0.username = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.websecurityscanner.v1.ScanConfig.Authentication.CustomAccount"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Describes authentication configuration for Identity-Aware-Proxy (IAP).
    public struct IapCredential: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Identity-Aware-Proxy (IAP) Authentication Configuration
      public var iapCredentials: OneOf_IapCredentials? = nil

      /// Initialize a new instance of `IapCredential`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = IapCredential().with { $0.iapTestServiceAccountInfo = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private enum CodingKeys: Swift.String, CodingKey {
        case iapTestServiceAccountInfo = "iapTestServiceAccountInfo"
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        var iapCredentials: OneOf_IapCredentials? = nil
        let iapCredentialsCheckAndSet = {
          if iapCredentials != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'iapCredentials'"))
          }
          iapCredentials = $0
        }
        if let iapTestServiceAccountInfo = try container.decodeIfPresent(
          ScanConfig.Authentication.IapCredential.IapTestServiceAccountInfo?.self,
          forKey: .iapTestServiceAccountInfo)
        {
          try iapCredentialsCheckAndSet(.iapTestServiceAccountInfo(iapTestServiceAccountInfo))
        }
        self.iapCredentials = iapCredentials
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        if let choice = self.iapCredentials {
          switch choice {
          case .iapTestServiceAccountInfo(let value):
            try container.encode(value, forKey: .iapTestServiceAccountInfo)
          }
        }
      }

      /// Describes authentication configuration when Web-Security-Scanner
      /// service account is added in Identity-Aware-Proxy (IAP) access policies.
      public struct IapTestServiceAccountInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Required. Describes OAuth2 client id of resources protected by
        /// Identity-Aware-Proxy (IAP).
        public var targetAudienceClientId: Swift.String = Swift.String()

        /// Initialize a new instance of `IapTestServiceAccountInfo`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = IapTestServiceAccountInfo().with { $0.targetAudienceClientId = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.cloud.websecurityscanner.v1.ScanConfig.Authentication.IapCredential.IapTestServiceAccountInfo"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      /// Identity-Aware-Proxy (IAP) Authentication Configuration
      public enum OneOf_IapCredentials: Codable, Equatable, Sendable {
        /// Authentication configuration when Web-Security-Scanner service
        /// account is added in Identity-Aware-Proxy (IAP) access policies.
        indirect case iapTestServiceAccountInfo(
          ScanConfig.Authentication.IapCredential.IapTestServiceAccountInfo?)
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.websecurityscanner.v1.ScanConfig.Authentication.IapCredential"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Required.
    /// Authentication configuration
    public enum OneOf_Authentication: Codable, Equatable, Sendable {
      /// Authentication using a Google account.
      @available(*, deprecated)
      indirect case googleAccount(ScanConfig.Authentication.GoogleAccount?)
      /// Authentication using a custom account.
      indirect case customAccount(ScanConfig.Authentication.CustomAccount?)
      /// Authentication using Identity-Aware-Proxy (IAP).
      indirect case iapCredential(ScanConfig.Authentication.IapCredential?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.websecurityscanner.v1.ScanConfig.Authentication"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Scan schedule configuration.
  public struct Schedule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// A timestamp indicates when the next run will be scheduled. The value is
    /// refreshed by the server after each run. If unspecified, it will default
    /// to current server time, which means the scan will be scheduled to start
    /// immediately.
    public var scheduleTime: GoogleCloudWkt.Timestamp? = nil

    /// Required. The duration of time between executions in days.
    public var intervalDurationDays: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `Schedule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Schedule().with { $0.scheduleTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.websecurityscanner.v1.ScanConfig.Schedule"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Type of user agents used for scanning.
  public enum UserAgent: Codable, Equatable, Sendable {
    /// The user agent is unknown. Service will default to CHROME_LINUX.
    case unspecified
    /// Chrome on Linux. This is the service default if unspecified.
    case chromeLinux
    /// Chrome on Android.
    case chromeAndroid
    /// Safari on IPhone.
    case safariIphone
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .chromeLinux: return 1
      case .chromeAndroid: return 2
      case .safariIphone: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "USER_AGENT_UNSPECIFIED"
      case .chromeLinux: return "CHROME_LINUX"
      case .chromeAndroid: return "CHROME_ANDROID"
      case .safariIphone: return "SAFARI_IPHONE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:UserAgent/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "USER_AGENT_UNSPECIFIED": self = .unspecified
      case "CHROME_LINUX": self = .chromeLinux
      case "CHROME_ANDROID": self = .chromeAndroid
      case "SAFARI_IPHONE": self = .safariIphone
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:UserAgent/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .chromeLinux
      case 2: self = .chromeAndroid
      case 3: self = .safariIphone
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .chromeLinux: return try container.encode(1)
      case .chromeAndroid: return try container.encode(2)
      case .safariIphone: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Scan risk levels supported by Web Security Scanner. LOW impact
  /// scanning will minimize requests with the potential to modify data. To
  /// achieve the maximum scan coverage, NORMAL risk level is recommended.
  public enum RiskLevel: Codable, Equatable, Sendable {
    /// Use default, which is NORMAL.
    case unspecified
    /// Normal scanning (Recommended)
    case normal
    /// Lower impact scanning
    case low
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .normal: return 1
      case .low: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RISK_LEVEL_UNSPECIFIED"
      case .normal: return "NORMAL"
      case .low: return "LOW"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:RiskLevel/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RISK_LEVEL_UNSPECIFIED": self = .unspecified
      case "NORMAL": self = .normal
      case "LOW": self = .low
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:RiskLevel/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .normal
      case 2: self = .low
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .normal: return try container.encode(1)
      case .low: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Controls export of scan configurations and results to Security
  /// Command Center.
  public enum ExportToSecurityCommandCenter: Codable, Equatable, Sendable {
    /// Use default, which is ENABLED.
    case unspecified
    /// Export results of this scan to Security Command Center.
    case enabled
    /// Do not export results of this scan to Security Command Center.
    case disabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .enabled: return 1
      case .disabled: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EXPORT_TO_SECURITY_COMMAND_CENTER_UNSPECIFIED"
      case .enabled: return "ENABLED"
      case .disabled: return "DISABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ExportToSecurityCommandCenter/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EXPORT_TO_SECURITY_COMMAND_CENTER_UNSPECIFIED": self = .unspecified
      case "ENABLED": self = .enabled
      case "DISABLED": self = .disabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ExportToSecurityCommandCenter/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .enabled
      case 2: self = .disabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .enabled: return try container.encode(1)
      case .disabled: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.websecurityscanner.v1.ScanConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
