// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Defines a custom error message used by CreateScanConfig and UpdateScanConfig
/// APIs when scan configuration validation fails. It is also reported as part of
/// a ScanRunErrorTrace message if scan validation fails due to a scan
/// configuration error.
public struct ScanConfigError: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Indicates the reason code for a configuration failure.
  public var code: ScanConfigError.Code = ScanConfigError.Code()

  /// Output only. Indicates the full name of the ScanConfig field that triggers this error,
  /// for example "scan_config.max_qps". This field is provided for
  /// troubleshooting purposes only and its actual value can change in the
  /// future.
  public var fieldName: Swift.String = Swift.String()

  /// Initialize a new instance of `ScanConfigError`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ScanConfigError().with { $0.code = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Output only.
  /// Defines an error reason code.
  /// Next id: 44
  public enum Code: Codable, Equatable, Sendable {
    /// There is no error.
    case ok
    /// Indicates an internal server error.
    /// Please DO NOT USE THIS ERROR CODE unless the root cause is truly unknown.
    case internalError
    /// One of the seed URLs is an App Engine URL but we cannot validate the scan
    /// settings due to an App Engine API backend error.
    case appengineApiBackendError
    /// One of the seed URLs is an App Engine URL but we cannot access the
    /// App Engine API to validate scan settings.
    case appengineApiNotAccessible
    /// One of the seed URLs is an App Engine URL but the Default Host of the
    /// App Engine is not set.
    case appengineDefaultHostMissing
    /// Google corporate accounts can not be used for scanning.
    case cannotUseGoogleComAccount
    /// The account of the scan creator can not be used for scanning.
    case cannotUseOwnerAccount
    /// This scan targets Compute Engine, but we cannot validate scan settings
    /// due to a Compute Engine API backend error.
    case computeApiBackendError
    /// This scan targets Compute Engine, but we cannot access the Compute Engine
    /// API to validate the scan settings.
    case computeApiNotAccessible
    /// The Custom Login URL does not belong to the current project.
    case customLoginUrlDoesNotBelongToCurrentProject
    /// The Custom Login URL is malformed (can not be parsed).
    case customLoginUrlMalformed
    /// The Custom Login URL is mapped to a non-routable IP address in DNS.
    case customLoginUrlMappedToNonRoutableAddress
    /// The Custom Login URL is mapped to an IP address which is not reserved for
    /// the current project.
    case customLoginUrlMappedToUnreservedAddress
    /// The Custom Login URL has a non-routable IP address.
    case customLoginUrlHasNonRoutableIpAddress
    /// The Custom Login URL has an IP address which is not reserved for the
    /// current project.
    case customLoginUrlHasUnreservedIpAddress
    /// Another scan with the same name (case-sensitive) already exists.
    case duplicateScanName
    /// A field is set to an invalid value.
    case invalidFieldValue
    /// There was an error trying to authenticate to the scan target.
    case failedToAuthenticateToTarget
    /// Finding type value is not specified in the list findings request.
    case findingTypeUnspecified
    /// Scan targets Compute Engine, yet current project was not whitelisted for
    /// Google Compute Engine Scanning Alpha access.
    case forbiddenToScanCompute
    /// The supplied filter is malformed. For example, it can not be parsed, does
    /// not have a filter type in expression, or the same filter type appears
    /// more than once.
    case malformedFilter
    /// The supplied resource name is malformed (can not be parsed).
    case malformedResourceName
    /// The current project is not in an active state.
    case projectInactive
    /// A required field is not set.
    case requiredField
    /// Project id, scanconfig id, scanrun id, or finding id are not consistent
    /// with each other in resource name.
    case resourceNameInconsistent
    /// The scan being requested to start is already running.
    case scanAlreadyRunning
    /// The scan that was requested to be stopped is not running.
    case scanNotRunning
    /// One of the seed URLs does not belong to the current project.
    case seedUrlDoesNotBelongToCurrentProject
    /// One of the seed URLs is malformed (can not be parsed).
    case seedUrlMalformed
    /// One of the seed URLs is mapped to a non-routable IP address in DNS.
    case seedUrlMappedToNonRoutableAddress
    /// One of the seed URLs is mapped to an IP address which is not reserved
    /// for the current project.
    case seedUrlMappedToUnreservedAddress
    /// One of the seed URLs has on-routable IP address.
    case seedUrlHasNonRoutableIpAddress
    /// One of the seed URLs has an IP address that is not reserved
    /// for the current project.
    case seedUrlHasUnreservedIpAddress
    /// The Web Security Scanner service account is not configured under the
    /// project.
    case serviceAccountNotConfigured
    /// A project has reached the maximum number of scans.
    case tooManyScans
    /// Resolving the details of the current project fails.
    case unableToResolveProjectInfo
    /// One or more blacklist patterns were in the wrong format.
    case unsupportedBlacklistPatternFormat
    /// The supplied filter is not supported.
    case unsupportedFilter
    /// The supplied finding type is not supported. For example, we do not
    /// provide findings of the given finding type.
    case unsupportedFindingType
    /// The URL scheme of one or more of the supplied URLs is not supported.
    case unsupportedUrlScheme
    /// User tries to update managed scan
    case forbiddenUpdateToManagedScan
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .ok
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .ok: return 0
      case .internalError: return 1
      case .appengineApiBackendError: return 2
      case .appengineApiNotAccessible: return 3
      case .appengineDefaultHostMissing: return 4
      case .cannotUseGoogleComAccount: return 6
      case .cannotUseOwnerAccount: return 7
      case .computeApiBackendError: return 8
      case .computeApiNotAccessible: return 9
      case .customLoginUrlDoesNotBelongToCurrentProject: return 10
      case .customLoginUrlMalformed: return 11
      case .customLoginUrlMappedToNonRoutableAddress: return 12
      case .customLoginUrlMappedToUnreservedAddress: return 13
      case .customLoginUrlHasNonRoutableIpAddress: return 14
      case .customLoginUrlHasUnreservedIpAddress: return 15
      case .duplicateScanName: return 16
      case .invalidFieldValue: return 18
      case .failedToAuthenticateToTarget: return 19
      case .findingTypeUnspecified: return 20
      case .forbiddenToScanCompute: return 21
      case .malformedFilter: return 22
      case .malformedResourceName: return 23
      case .projectInactive: return 24
      case .requiredField: return 25
      case .resourceNameInconsistent: return 26
      case .scanAlreadyRunning: return 27
      case .scanNotRunning: return 28
      case .seedUrlDoesNotBelongToCurrentProject: return 29
      case .seedUrlMalformed: return 30
      case .seedUrlMappedToNonRoutableAddress: return 31
      case .seedUrlMappedToUnreservedAddress: return 32
      case .seedUrlHasNonRoutableIpAddress: return 33
      case .seedUrlHasUnreservedIpAddress: return 35
      case .serviceAccountNotConfigured: return 36
      case .tooManyScans: return 37
      case .unableToResolveProjectInfo: return 38
      case .unsupportedBlacklistPatternFormat: return 39
      case .unsupportedFilter: return 40
      case .unsupportedFindingType: return 41
      case .unsupportedUrlScheme: return 42
      case .forbiddenUpdateToManagedScan: return 43
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .ok: return "OK"
      case .internalError: return "INTERNAL_ERROR"
      case .appengineApiBackendError: return "APPENGINE_API_BACKEND_ERROR"
      case .appengineApiNotAccessible: return "APPENGINE_API_NOT_ACCESSIBLE"
      case .appengineDefaultHostMissing: return "APPENGINE_DEFAULT_HOST_MISSING"
      case .cannotUseGoogleComAccount: return "CANNOT_USE_GOOGLE_COM_ACCOUNT"
      case .cannotUseOwnerAccount: return "CANNOT_USE_OWNER_ACCOUNT"
      case .computeApiBackendError: return "COMPUTE_API_BACKEND_ERROR"
      case .computeApiNotAccessible: return "COMPUTE_API_NOT_ACCESSIBLE"
      case .customLoginUrlDoesNotBelongToCurrentProject:
        return "CUSTOM_LOGIN_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT"
      case .customLoginUrlMalformed: return "CUSTOM_LOGIN_URL_MALFORMED"
      case .customLoginUrlMappedToNonRoutableAddress:
        return "CUSTOM_LOGIN_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS"
      case .customLoginUrlMappedToUnreservedAddress:
        return "CUSTOM_LOGIN_URL_MAPPED_TO_UNRESERVED_ADDRESS"
      case .customLoginUrlHasNonRoutableIpAddress:
        return "CUSTOM_LOGIN_URL_HAS_NON_ROUTABLE_IP_ADDRESS"
      case .customLoginUrlHasUnreservedIpAddress:
        return "CUSTOM_LOGIN_URL_HAS_UNRESERVED_IP_ADDRESS"
      case .duplicateScanName: return "DUPLICATE_SCAN_NAME"
      case .invalidFieldValue: return "INVALID_FIELD_VALUE"
      case .failedToAuthenticateToTarget: return "FAILED_TO_AUTHENTICATE_TO_TARGET"
      case .findingTypeUnspecified: return "FINDING_TYPE_UNSPECIFIED"
      case .forbiddenToScanCompute: return "FORBIDDEN_TO_SCAN_COMPUTE"
      case .malformedFilter: return "MALFORMED_FILTER"
      case .malformedResourceName: return "MALFORMED_RESOURCE_NAME"
      case .projectInactive: return "PROJECT_INACTIVE"
      case .requiredField: return "REQUIRED_FIELD"
      case .resourceNameInconsistent: return "RESOURCE_NAME_INCONSISTENT"
      case .scanAlreadyRunning: return "SCAN_ALREADY_RUNNING"
      case .scanNotRunning: return "SCAN_NOT_RUNNING"
      case .seedUrlDoesNotBelongToCurrentProject:
        return "SEED_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT"
      case .seedUrlMalformed: return "SEED_URL_MALFORMED"
      case .seedUrlMappedToNonRoutableAddress: return "SEED_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS"
      case .seedUrlMappedToUnreservedAddress: return "SEED_URL_MAPPED_TO_UNRESERVED_ADDRESS"
      case .seedUrlHasNonRoutableIpAddress: return "SEED_URL_HAS_NON_ROUTABLE_IP_ADDRESS"
      case .seedUrlHasUnreservedIpAddress: return "SEED_URL_HAS_UNRESERVED_IP_ADDRESS"
      case .serviceAccountNotConfigured: return "SERVICE_ACCOUNT_NOT_CONFIGURED"
      case .tooManyScans: return "TOO_MANY_SCANS"
      case .unableToResolveProjectInfo: return "UNABLE_TO_RESOLVE_PROJECT_INFO"
      case .unsupportedBlacklistPatternFormat: return "UNSUPPORTED_BLACKLIST_PATTERN_FORMAT"
      case .unsupportedFilter: return "UNSUPPORTED_FILTER"
      case .unsupportedFindingType: return "UNSUPPORTED_FINDING_TYPE"
      case .unsupportedUrlScheme: return "UNSUPPORTED_URL_SCHEME"
      case .forbiddenUpdateToManagedScan: return "FORBIDDEN_UPDATE_TO_MANAGED_SCAN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Code/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CODE_UNSPECIFIED": self = .ok
      case "OK": self = .ok
      case "INTERNAL_ERROR": self = .internalError
      case "APPENGINE_API_BACKEND_ERROR": self = .appengineApiBackendError
      case "APPENGINE_API_NOT_ACCESSIBLE": self = .appengineApiNotAccessible
      case "APPENGINE_DEFAULT_HOST_MISSING": self = .appengineDefaultHostMissing
      case "CANNOT_USE_GOOGLE_COM_ACCOUNT": self = .cannotUseGoogleComAccount
      case "CANNOT_USE_OWNER_ACCOUNT": self = .cannotUseOwnerAccount
      case "COMPUTE_API_BACKEND_ERROR": self = .computeApiBackendError
      case "COMPUTE_API_NOT_ACCESSIBLE": self = .computeApiNotAccessible
      case "CUSTOM_LOGIN_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT":
        self = .customLoginUrlDoesNotBelongToCurrentProject
      case "CUSTOM_LOGIN_URL_MALFORMED": self = .customLoginUrlMalformed
      case "CUSTOM_LOGIN_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS":
        self = .customLoginUrlMappedToNonRoutableAddress
      case "CUSTOM_LOGIN_URL_MAPPED_TO_UNRESERVED_ADDRESS":
        self = .customLoginUrlMappedToUnreservedAddress
      case "CUSTOM_LOGIN_URL_HAS_NON_ROUTABLE_IP_ADDRESS":
        self = .customLoginUrlHasNonRoutableIpAddress
      case "CUSTOM_LOGIN_URL_HAS_UNRESERVED_IP_ADDRESS":
        self = .customLoginUrlHasUnreservedIpAddress
      case "DUPLICATE_SCAN_NAME": self = .duplicateScanName
      case "INVALID_FIELD_VALUE": self = .invalidFieldValue
      case "FAILED_TO_AUTHENTICATE_TO_TARGET": self = .failedToAuthenticateToTarget
      case "FINDING_TYPE_UNSPECIFIED": self = .findingTypeUnspecified
      case "FORBIDDEN_TO_SCAN_COMPUTE": self = .forbiddenToScanCompute
      case "FORBIDDEN_UPDATE_TO_MANAGED_SCAN": self = .forbiddenUpdateToManagedScan
      case "MALFORMED_FILTER": self = .malformedFilter
      case "MALFORMED_RESOURCE_NAME": self = .malformedResourceName
      case "PROJECT_INACTIVE": self = .projectInactive
      case "REQUIRED_FIELD": self = .requiredField
      case "RESOURCE_NAME_INCONSISTENT": self = .resourceNameInconsistent
      case "SCAN_ALREADY_RUNNING": self = .scanAlreadyRunning
      case "SCAN_NOT_RUNNING": self = .scanNotRunning
      case "SEED_URL_DOES_NOT_BELONG_TO_CURRENT_PROJECT":
        self = .seedUrlDoesNotBelongToCurrentProject
      case "SEED_URL_MALFORMED": self = .seedUrlMalformed
      case "SEED_URL_MAPPED_TO_NON_ROUTABLE_ADDRESS": self = .seedUrlMappedToNonRoutableAddress
      case "SEED_URL_MAPPED_TO_UNRESERVED_ADDRESS": self = .seedUrlMappedToUnreservedAddress
      case "SEED_URL_HAS_NON_ROUTABLE_IP_ADDRESS": self = .seedUrlHasNonRoutableIpAddress
      case "SEED_URL_HAS_UNRESERVED_IP_ADDRESS": self = .seedUrlHasUnreservedIpAddress
      case "SERVICE_ACCOUNT_NOT_CONFIGURED": self = .serviceAccountNotConfigured
      case "TOO_MANY_SCANS": self = .tooManyScans
      case "UNABLE_TO_RESOLVE_PROJECT_INFO": self = .unableToResolveProjectInfo
      case "UNSUPPORTED_BLACKLIST_PATTERN_FORMAT": self = .unsupportedBlacklistPatternFormat
      case "UNSUPPORTED_FILTER": self = .unsupportedFilter
      case "UNSUPPORTED_FINDING_TYPE": self = .unsupportedFindingType
      case "UNSUPPORTED_URL_SCHEME": self = .unsupportedUrlScheme
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Code/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .ok
      case 1: self = .internalError
      case 2: self = .appengineApiBackendError
      case 3: self = .appengineApiNotAccessible
      case 4: self = .appengineDefaultHostMissing
      case 6: self = .cannotUseGoogleComAccount
      case 7: self = .cannotUseOwnerAccount
      case 8: self = .computeApiBackendError
      case 9: self = .computeApiNotAccessible
      case 10: self = .customLoginUrlDoesNotBelongToCurrentProject
      case 11: self = .customLoginUrlMalformed
      case 12: self = .customLoginUrlMappedToNonRoutableAddress
      case 13: self = .customLoginUrlMappedToUnreservedAddress
      case 14: self = .customLoginUrlHasNonRoutableIpAddress
      case 15: self = .customLoginUrlHasUnreservedIpAddress
      case 16: self = .duplicateScanName
      case 18: self = .invalidFieldValue
      case 19: self = .failedToAuthenticateToTarget
      case 20: self = .findingTypeUnspecified
      case 21: self = .forbiddenToScanCompute
      case 22: self = .malformedFilter
      case 23: self = .malformedResourceName
      case 24: self = .projectInactive
      case 25: self = .requiredField
      case 26: self = .resourceNameInconsistent
      case 27: self = .scanAlreadyRunning
      case 28: self = .scanNotRunning
      case 29: self = .seedUrlDoesNotBelongToCurrentProject
      case 30: self = .seedUrlMalformed
      case 31: self = .seedUrlMappedToNonRoutableAddress
      case 32: self = .seedUrlMappedToUnreservedAddress
      case 33: self = .seedUrlHasNonRoutableIpAddress
      case 35: self = .seedUrlHasUnreservedIpAddress
      case 36: self = .serviceAccountNotConfigured
      case 37: self = .tooManyScans
      case 38: self = .unableToResolveProjectInfo
      case 39: self = .unsupportedBlacklistPatternFormat
      case 40: self = .unsupportedFilter
      case 41: self = .unsupportedFindingType
      case 42: self = .unsupportedUrlScheme
      case 43: self = .forbiddenUpdateToManagedScan
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .ok: return try container.encode(0)
      case .internalError: return try container.encode(1)
      case .appengineApiBackendError: return try container.encode(2)
      case .appengineApiNotAccessible: return try container.encode(3)
      case .appengineDefaultHostMissing: return try container.encode(4)
      case .cannotUseGoogleComAccount: return try container.encode(6)
      case .cannotUseOwnerAccount: return try container.encode(7)
      case .computeApiBackendError: return try container.encode(8)
      case .computeApiNotAccessible: return try container.encode(9)
      case .customLoginUrlDoesNotBelongToCurrentProject: return try container.encode(10)
      case .customLoginUrlMalformed: return try container.encode(11)
      case .customLoginUrlMappedToNonRoutableAddress: return try container.encode(12)
      case .customLoginUrlMappedToUnreservedAddress: return try container.encode(13)
      case .customLoginUrlHasNonRoutableIpAddress: return try container.encode(14)
      case .customLoginUrlHasUnreservedIpAddress: return try container.encode(15)
      case .duplicateScanName: return try container.encode(16)
      case .invalidFieldValue: return try container.encode(18)
      case .failedToAuthenticateToTarget: return try container.encode(19)
      case .findingTypeUnspecified: return try container.encode(20)
      case .forbiddenToScanCompute: return try container.encode(21)
      case .malformedFilter: return try container.encode(22)
      case .malformedResourceName: return try container.encode(23)
      case .projectInactive: return try container.encode(24)
      case .requiredField: return try container.encode(25)
      case .resourceNameInconsistent: return try container.encode(26)
      case .scanAlreadyRunning: return try container.encode(27)
      case .scanNotRunning: return try container.encode(28)
      case .seedUrlDoesNotBelongToCurrentProject: return try container.encode(29)
      case .seedUrlMalformed: return try container.encode(30)
      case .seedUrlMappedToNonRoutableAddress: return try container.encode(31)
      case .seedUrlMappedToUnreservedAddress: return try container.encode(32)
      case .seedUrlHasNonRoutableIpAddress: return try container.encode(33)
      case .seedUrlHasUnreservedIpAddress: return try container.encode(35)
      case .serviceAccountNotConfigured: return try container.encode(36)
      case .tooManyScans: return try container.encode(37)
      case .unableToResolveProjectInfo: return try container.encode(38)
      case .unsupportedBlacklistPatternFormat: return try container.encode(39)
      case .unsupportedFilter: return try container.encode(40)
      case .unsupportedFindingType: return try container.encode(41)
      case .unsupportedUrlScheme: return try container.encode(42)
      case .forbiddenUpdateToManagedScan: return try container.encode(43)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.websecurityscanner.v1.ScanConfigError"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
