// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Output only.
/// Defines an error trace message for a ScanRun.
public struct ScanRunErrorTrace: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Indicates the error reason code.
  public var code: ScanRunErrorTrace.Code = ScanRunErrorTrace.Code()

  /// Output only. If the scan encounters SCAN_CONFIG_ISSUE error, this field has the error
  /// message encountered during scan configuration validation that is performed
  /// before each scan run.
  public var scanConfigError: ScanConfigError? = nil

  /// Output only. If the scan encounters TOO_MANY_HTTP_ERRORS, this field indicates the most
  /// common HTTP error code, if such is available. For example, if this code is
  /// 404, the scan has encountered too many NOT_FOUND responses.
  public var mostCommonHttpErrorCode: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ScanRunErrorTrace`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ScanRunErrorTrace().with { $0.code = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let code = CodingKeys(stringValue: "code")
    static let scanConfigError = CodingKeys(stringValue: "scanConfigError")
    static let mostCommonHttpErrorCode = CodingKeys(stringValue: "mostCommonHttpErrorCode")

    static let _knownKeys: Set<Swift.String> = [
      "code",
      "scanConfigError",
      "mostCommonHttpErrorCode",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(ScanRunErrorTrace.Code.self, forKey: .code) {
      self.code = value
    }
    self.scanConfigError = try container.decodeIfPresent(
      ScanConfigError.self, forKey: .scanConfigError)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .mostCommonHttpErrorCode)
    {
      self.mostCommonHttpErrorCode = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.code, forKey: .code)
    try container.encodeIfPresent(self.scanConfigError, forKey: .scanConfigError)
    try container.encode(self.mostCommonHttpErrorCode, forKey: .mostCommonHttpErrorCode)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Output only.
  /// Defines an error reason code.
  /// Next id: 8
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Code: Codable, Equatable, Sendable {
    /// Default value is never used.
    case unspecified
    /// Indicates that the scan run failed due to an internal server error.
    case internalError
    /// Indicates a scan configuration error, usually due to outdated ScanConfig
    /// settings, such as starting_urls or the DNS configuration.
    case scanConfigIssue
    /// Indicates an authentication error, usually due to outdated ScanConfig
    /// authentication settings.
    case authenticationConfigIssue
    /// Indicates a scan operation timeout, usually caused by a very large site.
    case timedOutWhileScanning
    /// Indicates that a scan encountered excessive redirects, either to
    /// authentication or some other page outside of the scan scope.
    case tooManyRedirects
    /// Indicates that a scan encountered numerous errors from the web site
    /// pages. When available, most_common_http_error_code field indicates the
    /// most common HTTP error code encountered during the scan.
    case tooManyHttpErrors
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .internalError: return 1
      case .scanConfigIssue: return 2
      case .authenticationConfigIssue: return 3
      case .timedOutWhileScanning: return 4
      case .tooManyRedirects: return 5
      case .tooManyHttpErrors: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CODE_UNSPECIFIED"
      case .internalError: return "INTERNAL_ERROR"
      case .scanConfigIssue: return "SCAN_CONFIG_ISSUE"
      case .authenticationConfigIssue: return "AUTHENTICATION_CONFIG_ISSUE"
      case .timedOutWhileScanning: return "TIMED_OUT_WHILE_SCANNING"
      case .tooManyRedirects: return "TOO_MANY_REDIRECTS"
      case .tooManyHttpErrors: return "TOO_MANY_HTTP_ERRORS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Code/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CODE_UNSPECIFIED": self = .unspecified
      case "INTERNAL_ERROR": self = .internalError
      case "SCAN_CONFIG_ISSUE": self = .scanConfigIssue
      case "AUTHENTICATION_CONFIG_ISSUE": self = .authenticationConfigIssue
      case "TIMED_OUT_WHILE_SCANNING": self = .timedOutWhileScanning
      case "TOO_MANY_REDIRECTS": self = .tooManyRedirects
      case "TOO_MANY_HTTP_ERRORS": self = .tooManyHttpErrors
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Code/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .internalError
      case 2: self = .scanConfigIssue
      case 3: self = .authenticationConfigIssue
      case 4: self = .timedOutWhileScanning
      case 5: self = .tooManyRedirects
      case 6: self = .tooManyHttpErrors
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CODE_UNSPECIFIED")
      case .internalError: return try container.encode("INTERNAL_ERROR")
      case .scanConfigIssue: return try container.encode("SCAN_CONFIG_ISSUE")
      case .authenticationConfigIssue: return try container.encode("AUTHENTICATION_CONFIG_ISSUE")
      case .timedOutWhileScanning: return try container.encode("TIMED_OUT_WHILE_SCANNING")
      case .tooManyRedirects: return try container.encode("TOO_MANY_REDIRECTS")
      case .tooManyHttpErrors: return try container.encode("TOO_MANY_HTTP_ERRORS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.websecurityscanner.v1.ScanRunErrorTrace"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
