// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A ScanRun is a output-only resource representing an actual run of the scan.
/// Next id: 12
public struct ScanRun: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the ScanRun. The name follows the format of
  /// 'projects/{projectId}/scanConfigs/{scanConfigId}/scanRuns/{scanRunId}'.
  /// The ScanRun IDs are generated by the system.
  public var name: Swift.String = Swift.String()

  /// Output only. The execution state of the ScanRun.
  public var executionState: ScanRun.ExecutionState = ScanRun.ExecutionState()

  /// Output only. The result state of the ScanRun. This field is only available after the
  /// execution state reaches "FINISHED".
  public var resultState: ScanRun.ResultState = ScanRun.ResultState()

  /// Output only. The time at which the ScanRun started.
  public var startTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time at which the ScanRun reached termination state - that the ScanRun
  /// is either finished or stopped by user.
  public var endTime: GoogleWKT.Timestamp? = nil

  /// Output only. The number of URLs crawled during this ScanRun. If the scan is in progress,
  /// the value represents the number of URLs crawled up to now.
  public var urlsCrawledCount: Swift.Int64 = Swift.Int64()

  /// Output only. The number of URLs tested during this ScanRun. If the scan is in progress,
  /// the value represents the number of URLs tested up to now. The number of
  /// URLs tested is usually larger than the number URLS crawled because
  /// typically a crawled URL is tested with multiple test payloads.
  public var urlsTestedCount: Swift.Int64 = Swift.Int64()

  /// Output only. Whether the scan run has found any vulnerabilities.
  public var hasVulnerabilities: Swift.Bool = Swift.Bool()

  /// Output only. The percentage of total completion ranging from 0 to 100.
  /// If the scan is in queue, the value is 0.
  /// If the scan is running, the value ranges from 0 to 100.
  /// If the scan is finished, the value is 100.
  public var progressPercent: Swift.Int32 = Swift.Int32()

  /// Output only. If result_state is an ERROR, this field provides the primary reason for
  /// scan's termination and more details, if such are available.
  public var errorTrace: ScanRunErrorTrace? = nil

  /// Output only. A list of warnings, if such are encountered during this scan run.
  public var warningTraces: [ScanRunWarningTrace] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ScanRun`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ScanRun().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let executionState = CodingKeys(stringValue: "executionState")
    static let resultState = CodingKeys(stringValue: "resultState")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let urlsCrawledCount = CodingKeys(stringValue: "urlsCrawledCount")
    static let urlsTestedCount = CodingKeys(stringValue: "urlsTestedCount")
    static let hasVulnerabilities = CodingKeys(stringValue: "hasVulnerabilities")
    static let progressPercent = CodingKeys(stringValue: "progressPercent")
    static let errorTrace = CodingKeys(stringValue: "errorTrace")
    static let warningTraces = CodingKeys(stringValue: "warningTraces")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "executionState",
      "resultState",
      "startTime",
      "endTime",
      "urlsCrawledCount",
      "urlsTestedCount",
      "hasVulnerabilities",
      "progressPercent",
      "errorTrace",
      "warningTraces",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(
      ScanRun.ExecutionState.self, forKey: .executionState)
    {
      self.executionState = value
    }
    if let value = try container.decodeIfPresent(ScanRun.ResultState.self, forKey: .resultState) {
      self.resultState = value
    }
    self.startTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .urlsCrawledCount) {
      self.urlsCrawledCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .urlsTestedCount) {
      self.urlsTestedCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .hasVulnerabilities) {
      self.hasVulnerabilities = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .progressPercent) {
      self.progressPercent = value
    }
    self.errorTrace = try container.decodeIfPresent(ScanRunErrorTrace.self, forKey: .errorTrace)
    if let value = try container.decodeIfPresent([ScanRunWarningTrace].self, forKey: .warningTraces)
    {
      self.warningTraces = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.executionState, forKey: .executionState)
    try container.encode(self.resultState, forKey: .resultState)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.urlsCrawledCount, forKey: .urlsCrawledCount)
    try container.encode(self.urlsTestedCount, forKey: .urlsTestedCount)
    try container.encode(self.hasVulnerabilities, forKey: .hasVulnerabilities)
    try container.encode(self.progressPercent, forKey: .progressPercent)
    try container.encodeIfPresent(self.errorTrace, forKey: .errorTrace)
    try container.encode(self.warningTraces, forKey: .warningTraces)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Types of ScanRun execution state.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ExecutionState: Codable, Equatable, Sendable {
    /// Represents an invalid state caused by internal server error. This value
    /// should never be returned.
    case unspecified
    /// The scan is waiting in the queue.
    case queued
    /// The scan is in progress.
    case scanning
    /// The scan is either finished or stopped by user.
    case finished
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .queued: return 1
      case .scanning: return 2
      case .finished: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EXECUTION_STATE_UNSPECIFIED"
      case .queued: return "QUEUED"
      case .scanning: return "SCANNING"
      case .finished: return "FINISHED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ExecutionState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EXECUTION_STATE_UNSPECIFIED": self = .unspecified
      case "QUEUED": self = .queued
      case "SCANNING": self = .scanning
      case "FINISHED": self = .finished
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ExecutionState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .queued
      case 2: self = .scanning
      case 3: self = .finished
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("EXECUTION_STATE_UNSPECIFIED")
      case .queued: return try container.encode("QUEUED")
      case .scanning: return try container.encode("SCANNING")
      case .finished: return try container.encode("FINISHED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Types of ScanRun result state.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ResultState: Codable, Equatable, Sendable {
    /// Default value. This value is returned when the ScanRun is not yet
    /// finished.
    case unspecified
    /// The scan finished without errors.
    case success
    /// The scan finished with errors.
    case error
    /// The scan was terminated by user.
    case killed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .success: return 1
      case .error: return 2
      case .killed: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RESULT_STATE_UNSPECIFIED"
      case .success: return "SUCCESS"
      case .error: return "ERROR"
      case .killed: return "KILLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ResultState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RESULT_STATE_UNSPECIFIED": self = .unspecified
      case "SUCCESS": self = .success
      case "ERROR": self = .error
      case "KILLED": self = .killed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ResultState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .success
      case 2: self = .error
      case 3: self = .killed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("RESULT_STATE_UNSPECIFIED")
      case .success: return try container.encode("SUCCESS")
      case .error: return try container.encode("ERROR")
      case .killed: return try container.encode("KILLED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.websecurityscanner.v1.ScanRun"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
