// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Output only.
/// Defines a warning trace message for ScanRun. Warning traces provide customers
/// with useful information that helps make the scanning process more effective.
public struct ScanRunWarningTrace: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Indicates the warning code.
  public var code: ScanRunWarningTrace.Code = ScanRunWarningTrace.Code()

  /// Initialize a new instance of `ScanRunWarningTrace`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ScanRunWarningTrace().with { $0.code = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Output only.
  /// Defines a warning message code.
  /// Next id: 6
  public enum Code: Codable, Equatable, Sendable {
    /// Default value is never used.
    case unspecified
    /// Indicates that a scan discovered an unexpectedly low number of URLs. This
    /// is sometimes caused by complex navigation features or by using a single
    /// URL for numerous pages.
    case insufficientCrawlResults
    /// Indicates that a scan discovered too many URLs to test, or excessive
    /// redundant URLs.
    case tooManyCrawlResults
    /// Indicates that too many tests have been generated for the scan. Customer
    /// should try reducing the number of starting URLs, increasing the QPS rate,
    /// or narrowing down the scope of the scan using the excluded patterns.
    case tooManyFuzzTasks
    /// Indicates that a scan is blocked by IAP.
    case blockedByIap
    /// Indicates that no seeds is found for a scan
    case noStartingUrlFoundForManagedScan
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .insufficientCrawlResults: return 1
      case .tooManyCrawlResults: return 2
      case .tooManyFuzzTasks: return 3
      case .blockedByIap: return 4
      case .noStartingUrlFoundForManagedScan: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CODE_UNSPECIFIED"
      case .insufficientCrawlResults: return "INSUFFICIENT_CRAWL_RESULTS"
      case .tooManyCrawlResults: return "TOO_MANY_CRAWL_RESULTS"
      case .tooManyFuzzTasks: return "TOO_MANY_FUZZ_TASKS"
      case .blockedByIap: return "BLOCKED_BY_IAP"
      case .noStartingUrlFoundForManagedScan: return "NO_STARTING_URL_FOUND_FOR_MANAGED_SCAN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Code/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CODE_UNSPECIFIED": self = .unspecified
      case "INSUFFICIENT_CRAWL_RESULTS": self = .insufficientCrawlResults
      case "TOO_MANY_CRAWL_RESULTS": self = .tooManyCrawlResults
      case "TOO_MANY_FUZZ_TASKS": self = .tooManyFuzzTasks
      case "BLOCKED_BY_IAP": self = .blockedByIap
      case "NO_STARTING_URL_FOUND_FOR_MANAGED_SCAN": self = .noStartingUrlFoundForManagedScan
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Code/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .insufficientCrawlResults
      case 2: self = .tooManyCrawlResults
      case 3: self = .tooManyFuzzTasks
      case 4: self = .blockedByIap
      case 5: self = .noStartingUrlFoundForManagedScan
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .insufficientCrawlResults: return try container.encode(1)
      case .tooManyCrawlResults: return try container.encode(2)
      case .tooManyFuzzTasks: return try container.encode(3)
      case .blockedByIap: return try container.encode(4)
      case .noStartingUrlFoundForManagedScan: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.websecurityscanner.v1.ScanRunWarningTrace"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
