// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  final class WebSecurityScannerRetry: WebSecurityScannerStub {
    let inner: any WebSecurityScannerStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any WebSecurityScannerStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createScanConfig(
      request: CreateScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateScanConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ScanConfig
          in
          return try await self.inner.createScanConfig(request: r, options: o)
        })
    }

    public func deleteScanConfig(
      request: DeleteScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteScanConfigRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteScanConfig(request: r, options: o)
        })
    }

    public func getScanConfig(
      request: GetScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetScanConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ScanConfig
          in
          return try await self.inner.getScanConfig(request: r, options: o)
        })
    }

    public func listScanConfigs(
      request: ListScanConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListScanConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListScanConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ListScanConfigsResponse
          in
          return try await self.inner.listScanConfigs(request: r, options: o)
        })
    }

    public func updateScanConfig(
      request: UpdateScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateScanConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ScanConfig
          in
          return try await self.inner.updateScanConfig(request: r, options: o)
        })
    }

    public func startScanRun(
      request: StartScanRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: StartScanRunRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ScanRun
          in
          return try await self.inner.startScanRun(request: r, options: o)
        })
    }

    public func getScanRun(
      request: GetScanRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetScanRunRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ScanRun
          in
          return try await self.inner.getScanRun(request: r, options: o)
        })
    }

    public func listScanRuns(
      request: ListScanRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListScanRunsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListScanRunsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ListScanRunsResponse
          in
          return try await self.inner.listScanRuns(request: r, options: o)
        })
    }

    public func stopScanRun(
      request: StopScanRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: StopScanRunRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ScanRun
          in
          return try await self.inner.stopScanRun(request: r, options: o)
        })
    }

    public func listCrawledUrls(
      request: ListCrawledUrlsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListCrawledUrlsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListCrawledUrlsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ListCrawledUrlsResponse
          in
          return try await self.inner.listCrawledUrls(request: r, options: o)
        })
    }

    public func getFinding(
      request: GetFindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.Finding {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetFindingRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.Finding
          in
          return try await self.inner.getFinding(request: r, options: o)
        })
    }

    public func listFindings(
      request: ListFindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListFindingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ListFindingsResponse
          in
          return try await self.inner.listFindings(request: r, options: o)
        })
    }

    public func listFindingTypeStats(
      request: ListFindingTypeStatsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingTypeStatsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListFindingTypeStatsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ListFindingTypeStatsResponse
          in
          return try await self.inner.listFindingTypeStats(request: r, options: o)
        })
    }
  }
}
