// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class WebSecurityScannerLogging: WebSecurityScannerStub {
    let inner: any WebSecurityScannerStub
    let logger: Logger

    public init(_ inner: any WebSecurityScannerStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-websecurityscanner-v1"
      logger[metadataKey: "gcp.client.service"] = "websecurityscanner"
      logger[metadataKey: "gcp.experimental.swift.client"] = "WebSecurityScanner"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createScanConfig(
      request: CreateScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "createScanConfig",
        action: {
          (r: CreateScanConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ScanConfig
          in
          return try await self.inner.createScanConfig(request: r, options: o)
        })
    }

    public func deleteScanConfig(
      request: DeleteScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteScanConfig",
        action: {
          (r: DeleteScanConfigRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteScanConfig(request: r, options: o)
        })
    }

    public func getScanConfig(
      request: GetScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getScanConfig",
        action: {
          (r: GetScanConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ScanConfig
          in
          return try await self.inner.getScanConfig(request: r, options: o)
        })
    }

    public func listScanConfigs(
      request: ListScanConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListScanConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listScanConfigs",
        action: {
          (r: ListScanConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ListScanConfigsResponse
          in
          return try await self.inner.listScanConfigs(request: r, options: o)
        })
    }

    public func updateScanConfig(
      request: UpdateScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateScanConfig",
        action: {
          (r: UpdateScanConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ScanConfig
          in
          return try await self.inner.updateScanConfig(request: r, options: o)
        })
    }

    public func startScanRun(
      request: StartScanRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun {
      try await self._intercept(
        request: request,
        options: options,
        name: "startScanRun",
        action: {
          (r: StartScanRunRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ScanRun
          in
          return try await self.inner.startScanRun(request: r, options: o)
        })
    }

    public func getScanRun(
      request: GetScanRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun {
      try await self._intercept(
        request: request,
        options: options,
        name: "getScanRun",
        action: {
          (r: GetScanRunRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ScanRun
          in
          return try await self.inner.getScanRun(request: r, options: o)
        })
    }

    public func listScanRuns(
      request: ListScanRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListScanRunsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listScanRuns",
        action: {
          (r: ListScanRunsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ListScanRunsResponse
          in
          return try await self.inner.listScanRuns(request: r, options: o)
        })
    }

    public func stopScanRun(
      request: StopScanRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun {
      try await self._intercept(
        request: request,
        options: options,
        name: "stopScanRun",
        action: {
          (r: StopScanRunRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ScanRun
          in
          return try await self.inner.stopScanRun(request: r, options: o)
        })
    }

    public func listCrawledUrls(
      request: ListCrawledUrlsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListCrawledUrlsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCrawledUrls",
        action: {
          (r: ListCrawledUrlsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ListCrawledUrlsResponse
          in
          return try await self.inner.listCrawledUrls(request: r, options: o)
        })
    }

    public func getFinding(
      request: GetFindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.Finding {
      try await self._intercept(
        request: request,
        options: options,
        name: "getFinding",
        action: {
          (r: GetFindingRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.Finding
          in
          return try await self.inner.getFinding(request: r, options: o)
        })
    }

    public func listFindings(
      request: ListFindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listFindings",
        action: {
          (r: ListFindingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ListFindingsResponse
          in
          return try await self.inner.listFindings(request: r, options: o)
        })
    }

    public func listFindingTypeStats(
      request: ListFindingTypeStatsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingTypeStatsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listFindingTypeStats",
        action: {
          (r: ListFindingTypeStatsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWebSecurityScannerV1.ListFindingTypeStatsResponse
          in
          return try await self.inner.listFindingTypeStats(request: r, options: o)
        })
    }
  }
}
