// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol WebSecurityScannerStub {
    func createScanConfig(
      request: CreateScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig

    func deleteScanConfig(
      request: DeleteScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func getScanConfig(
      request: GetScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig

    func listScanConfigs(
      request: ListScanConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListScanConfigsResponse

    func updateScanConfig(
      request: UpdateScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig

    func startScanRun(
      request: StartScanRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun

    func getScanRun(
      request: GetScanRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun

    func listScanRuns(
      request: ListScanRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListScanRunsResponse

    func stopScanRun(
      request: StopScanRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun

    func listCrawledUrls(
      request: ListCrawledUrlsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListCrawledUrlsResponse

    func getFinding(
      request: GetFindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.Finding

    func listFindings(
      request: ListFindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingsResponse

    func listFindingTypeStats(
      request: ListFindingTypeStatsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingTypeStatsResponse
  }

  class WebSecurityScannerTransport: WebSecurityScannerStub {
    let inner: GoogleCloudGax.HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax.HTTPClient(
        from: options, withDefaultEndpoint: "https://websecurityscanner.googleapis.com")
    }

    public func createScanConfig(
      request: CreateScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/scanConfigs"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.scanConfig {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudWebSecurityScannerV1.ScanConfig.self, from: data)
    }

    public func deleteScanConfig(
      request: DeleteScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      _ = try await self.inner.rpc(for: req).get()
    }

    public func getScanConfig(
      request: GetScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudWebSecurityScannerV1.ScanConfig.self, from: data)
    }

    public func listScanConfigs(
      request: ListScanConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListScanConfigsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/scanConfigs"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudWebSecurityScannerV1.ListScanConfigsResponse.self, from: data)
    }

    public func updateScanConfig(
      request: UpdateScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.scanConfig.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.scan_config.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "PATCH"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.scanConfig {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudWebSecurityScannerV1.ScanConfig.self, from: data)
    }

    public func startScanRun(
      request: StartScanRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0):start"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudWebSecurityScannerV1.ScanRun.self, from: data)
    }

    public func getScanRun(
      request: GetScanRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudWebSecurityScannerV1.ScanRun.self, from: data)
    }

    public func listScanRuns(
      request: ListScanRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListScanRunsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/scanRuns"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudWebSecurityScannerV1.ListScanRunsResponse.self, from: data)
    }

    public func stopScanRun(
      request: StopScanRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0):stop"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudWebSecurityScannerV1.ScanRun.self, from: data)
    }

    public func listCrawledUrls(
      request: ListCrawledUrlsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListCrawledUrlsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/crawledUrls"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudWebSecurityScannerV1.ListCrawledUrlsResponse.self, from: data)
    }

    public func getFinding(
      request: GetFindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.Finding {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudWebSecurityScannerV1.Finding.self, from: data)
    }

    public func listFindings(
      request: ListFindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/findings"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudWebSecurityScannerV1.ListFindingsResponse.self, from: data)
    }

    public func listFindingTypeStats(
      request: ListFindingTypeStatsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingTypeStatsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/findingTypeStats"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudWebSecurityScannerV1.ListFindingTypeStatsResponse.self, from: data)
    }
  }
}
