// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax

/// Web Security Scanner Service identifies security vulnerabilities in web
/// applications hosted on Google Cloud. It crawls your application, and
/// attempts to exercise as many user inputs and event handlers as possible.
///
/// @Snippet(path: "WebSecurityScannerQuickstart")
public final class WebSecurityScannerClient: Clients.WebSecurityScannerProtocol, Sendable {
  let inner: any Clients.WebSecurityScannerStub

  /// Creates a new `WebSecurityScannerClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.WebSecurityScannerStub = try Clients.WebSecurityScannerTransport(options)
    inner = Clients.WebSecurityScannerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.WebSecurityScannerLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a new ScanConfig.
  ///
  /// @Snippet(path: "WebSecurityScanner_CreateScanConfig")
  public func createScanConfig(
    request: CreateScanConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig {
    try await self.inner.createScanConfig(request: request, options: options)
  }

  /// Deletes an existing ScanConfig and its child resources.
  ///
  /// @Snippet(path: "WebSecurityScanner_DeleteScanConfig")
  public func deleteScanConfig(
    request: DeleteScanConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteScanConfig(request: request, options: options)
  }

  /// Gets a ScanConfig.
  ///
  /// @Snippet(path: "WebSecurityScanner_GetScanConfig")
  public func getScanConfig(
    request: GetScanConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig {
    try await self.inner.getScanConfig(request: request, options: options)
  }

  /// Lists ScanConfigs under a given project.
  ///
  /// @Snippet(path: "WebSecurityScanner_ListScanConfigs")
  public func listScanConfigs(
    request: ListScanConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ListScanConfigsResponse {
    try await self.inner.listScanConfigs(request: request, options: options)
  }

  /// Lists ScanConfigs under a given project.
  ///
  /// @Snippet(path: "WebSecurityScanner_ListScanConfigs")
  public func listScanConfigs(
    byItem: ListScanConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ScanConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWebSecurityScannerV1.ListScanConfigsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listScanConfigs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Updates a ScanConfig. This method support partial update of a ScanConfig.
  ///
  /// @Snippet(path: "WebSecurityScanner_UpdateScanConfig")
  public func updateScanConfig(
    request: UpdateScanConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig {
    try await self.inner.updateScanConfig(request: request, options: options)
  }

  /// Start a ScanRun according to the given ScanConfig.
  ///
  /// @Snippet(path: "WebSecurityScanner_StartScanRun")
  public func startScanRun(
    request: StartScanRunRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun {
    try await self.inner.startScanRun(request: request, options: options)
  }

  /// Gets a ScanRun.
  ///
  /// @Snippet(path: "WebSecurityScanner_GetScanRun")
  public func getScanRun(
    request: GetScanRunRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun {
    try await self.inner.getScanRun(request: request, options: options)
  }

  /// Lists ScanRuns under a given ScanConfig, in descending order of ScanRun
  /// stop time.
  ///
  /// @Snippet(path: "WebSecurityScanner_ListScanRuns")
  public func listScanRuns(
    request: ListScanRunsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ListScanRunsResponse {
    try await self.inner.listScanRuns(request: request, options: options)
  }

  /// Lists ScanRuns under a given ScanConfig, in descending order of ScanRun
  /// stop time.
  ///
  /// @Snippet(path: "WebSecurityScanner_ListScanRuns")
  public func listScanRuns(
    byItem: ListScanRunsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ScanRun, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWebSecurityScannerV1.ListScanRunsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listScanRuns(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Stops a ScanRun. The stopped ScanRun is returned.
  ///
  /// @Snippet(path: "WebSecurityScanner_StopScanRun")
  public func stopScanRun(
    request: StopScanRunRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun {
    try await self.inner.stopScanRun(request: request, options: options)
  }

  /// List CrawledUrls under a given ScanRun.
  ///
  /// @Snippet(path: "WebSecurityScanner_ListCrawledUrls")
  public func listCrawledUrls(
    request: ListCrawledUrlsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ListCrawledUrlsResponse {
    try await self.inner.listCrawledUrls(request: request, options: options)
  }

  /// List CrawledUrls under a given ScanRun.
  ///
  /// @Snippet(path: "WebSecurityScanner_ListCrawledUrls")
  public func listCrawledUrls(
    byItem: ListCrawledUrlsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<CrawledUrl, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWebSecurityScannerV1.ListCrawledUrlsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listCrawledUrls(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets a Finding.
  ///
  /// @Snippet(path: "WebSecurityScanner_GetFinding")
  public func getFinding(
    request: GetFindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.Finding {
    try await self.inner.getFinding(request: request, options: options)
  }

  /// List Findings under a given ScanRun.
  ///
  /// @Snippet(path: "WebSecurityScanner_ListFindings")
  public func listFindings(
    request: ListFindingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingsResponse {
    try await self.inner.listFindings(request: request, options: options)
  }

  /// List Findings under a given ScanRun.
  ///
  /// @Snippet(path: "WebSecurityScanner_ListFindings")
  public func listFindings(
    byItem: ListFindingsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Finding, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listFindings(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// List all FindingTypeStats under a given ScanRun.
  ///
  /// @Snippet(path: "WebSecurityScanner_ListFindingTypeStats")
  public func listFindingTypeStats(
    request: ListFindingTypeStatsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingTypeStatsResponse {
    try await self.inner.listFindingTypeStats(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `WebSecurityScannerClient`.
  ///
  /// To mock `WebSecurityScannerClient` change your functions to receive
  /// `some WebSecurityScannerProtocol` or `any WebSecurityScannerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol WebSecurityScannerProtocol {
    /// See `WebSecurityScannerClient.createScanConfig`.
    func createScanConfig(request: CreateScanConfigRequest) async throws
      -> GoogleCloudWebSecurityScannerV1.ScanConfig

    /// See `WebSecurityScannerClient.deleteScanConfig`.
    func deleteScanConfig(request: DeleteScanConfigRequest) async throws

    /// See `WebSecurityScannerClient.getScanConfig`.
    func getScanConfig(request: GetScanConfigRequest) async throws
      -> GoogleCloudWebSecurityScannerV1.ScanConfig

    /// See `WebSecurityScannerClient.listScanConfigs`.
    func listScanConfigs(request: ListScanConfigsRequest) async throws
      -> GoogleCloudWebSecurityScannerV1.ListScanConfigsResponse

    /// See `WebSecurityScannerClient.listScanConfigs`.
    func listScanConfigs(
      byItem: ListScanConfigsRequest
    ) throws -> any AsyncSequence<ScanConfig, Swift.Error>

    /// See `WebSecurityScannerClient.updateScanConfig`.
    func updateScanConfig(request: UpdateScanConfigRequest) async throws
      -> GoogleCloudWebSecurityScannerV1.ScanConfig

    /// See `WebSecurityScannerClient.startScanRun`.
    func startScanRun(request: StartScanRunRequest) async throws
      -> GoogleCloudWebSecurityScannerV1.ScanRun

    /// See `WebSecurityScannerClient.getScanRun`.
    func getScanRun(request: GetScanRunRequest) async throws
      -> GoogleCloudWebSecurityScannerV1.ScanRun

    /// See `WebSecurityScannerClient.listScanRuns`.
    func listScanRuns(request: ListScanRunsRequest) async throws
      -> GoogleCloudWebSecurityScannerV1.ListScanRunsResponse

    /// See `WebSecurityScannerClient.listScanRuns`.
    func listScanRuns(
      byItem: ListScanRunsRequest
    ) throws -> any AsyncSequence<ScanRun, Swift.Error>

    /// See `WebSecurityScannerClient.stopScanRun`.
    func stopScanRun(request: StopScanRunRequest) async throws
      -> GoogleCloudWebSecurityScannerV1.ScanRun

    /// See `WebSecurityScannerClient.listCrawledUrls`.
    func listCrawledUrls(request: ListCrawledUrlsRequest) async throws
      -> GoogleCloudWebSecurityScannerV1.ListCrawledUrlsResponse

    /// See `WebSecurityScannerClient.listCrawledUrls`.
    func listCrawledUrls(
      byItem: ListCrawledUrlsRequest
    ) throws -> any AsyncSequence<CrawledUrl, Swift.Error>

    /// See `WebSecurityScannerClient.getFinding`.
    func getFinding(request: GetFindingRequest) async throws
      -> GoogleCloudWebSecurityScannerV1.Finding

    /// See `WebSecurityScannerClient.listFindings`.
    func listFindings(request: ListFindingsRequest) async throws
      -> GoogleCloudWebSecurityScannerV1.ListFindingsResponse

    /// See `WebSecurityScannerClient.listFindings`.
    func listFindings(
      byItem: ListFindingsRequest
    ) throws -> any AsyncSequence<Finding, Swift.Error>

    /// See `WebSecurityScannerClient.listFindingTypeStats`.
    func listFindingTypeStats(request: ListFindingTypeStatsRequest) async throws
      -> GoogleCloudWebSecurityScannerV1.ListFindingTypeStatsResponse

    /// See `WebSecurityScannerClient.createScanConfig`.
    func createScanConfig(
      request: CreateScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig

    /// See `WebSecurityScannerClient.deleteScanConfig`.
    func deleteScanConfig(
      request: DeleteScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `WebSecurityScannerClient.getScanConfig`.
    func getScanConfig(
      request: GetScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig

    /// See `WebSecurityScannerClient.listScanConfigs`.
    func listScanConfigs(
      request: ListScanConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListScanConfigsResponse

    /// See `WebSecurityScannerClient.listScanConfigs`.
    func listScanConfigs(
      byItem: ListScanConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ScanConfig, Swift.Error>

    /// See `WebSecurityScannerClient.updateScanConfig`.
    func updateScanConfig(
      request: UpdateScanConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig

    /// See `WebSecurityScannerClient.startScanRun`.
    func startScanRun(
      request: StartScanRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun

    /// See `WebSecurityScannerClient.getScanRun`.
    func getScanRun(
      request: GetScanRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun

    /// See `WebSecurityScannerClient.listScanRuns`.
    func listScanRuns(
      request: ListScanRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListScanRunsResponse

    /// See `WebSecurityScannerClient.listScanRuns`.
    func listScanRuns(
      byItem: ListScanRunsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ScanRun, Swift.Error>

    /// See `WebSecurityScannerClient.stopScanRun`.
    func stopScanRun(
      request: StopScanRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun

    /// See `WebSecurityScannerClient.listCrawledUrls`.
    func listCrawledUrls(
      request: ListCrawledUrlsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListCrawledUrlsResponse

    /// See `WebSecurityScannerClient.listCrawledUrls`.
    func listCrawledUrls(
      byItem: ListCrawledUrlsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<CrawledUrl, Swift.Error>

    /// See `WebSecurityScannerClient.getFinding`.
    func getFinding(
      request: GetFindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.Finding

    /// See `WebSecurityScannerClient.listFindings`.
    func listFindings(
      request: ListFindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingsResponse

    /// See `WebSecurityScannerClient.listFindings`.
    func listFindings(
      byItem: ListFindingsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Finding, Swift.Error>

    /// See `WebSecurityScannerClient.listFindingTypeStats`.
    func listFindingTypeStats(
      request: ListFindingTypeStatsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingTypeStatsResponse
  }
}

// Default implementations
extension Clients.WebSecurityScannerProtocol {
  public func createScanConfig(request: CreateScanConfigRequest) async throws
    -> GoogleCloudWebSecurityScannerV1.ScanConfig
  {
    try await self.createScanConfig(request: request, options: .init())
  }

  public func createScanConfig(
    request: CreateScanConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteScanConfig(request: DeleteScanConfigRequest) async throws {
    try await self.deleteScanConfig(request: request, options: .init())
  }

  public func deleteScanConfig(
    request: DeleteScanConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getScanConfig(request: GetScanConfigRequest) async throws
    -> GoogleCloudWebSecurityScannerV1.ScanConfig
  {
    try await self.getScanConfig(request: request, options: .init())
  }

  public func getScanConfig(
    request: GetScanConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listScanConfigs(request: ListScanConfigsRequest) async throws
    -> GoogleCloudWebSecurityScannerV1.ListScanConfigsResponse
  {
    try await self.listScanConfigs(request: request, options: .init())
  }

  public func listScanConfigs(
    request: ListScanConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ListScanConfigsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listScanConfigs(
    byItem: ListScanConfigsRequest
  ) throws -> any AsyncSequence<ScanConfig, Swift.Error> {
    try self.listScanConfigs(byItem: byItem, options: .init())
  }

  public func listScanConfigs(
    byItem: ListScanConfigsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ScanConfig, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWebSecurityScannerV1.ListScanConfigsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func updateScanConfig(request: UpdateScanConfigRequest) async throws
    -> GoogleCloudWebSecurityScannerV1.ScanConfig
  {
    try await self.updateScanConfig(request: request, options: .init())
  }

  public func updateScanConfig(
    request: UpdateScanConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ScanConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func startScanRun(request: StartScanRunRequest) async throws
    -> GoogleCloudWebSecurityScannerV1.ScanRun
  {
    try await self.startScanRun(request: request, options: .init())
  }

  public func startScanRun(
    request: StartScanRunRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getScanRun(request: GetScanRunRequest) async throws
    -> GoogleCloudWebSecurityScannerV1.ScanRun
  {
    try await self.getScanRun(request: request, options: .init())
  }

  public func getScanRun(
    request: GetScanRunRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listScanRuns(request: ListScanRunsRequest) async throws
    -> GoogleCloudWebSecurityScannerV1.ListScanRunsResponse
  {
    try await self.listScanRuns(request: request, options: .init())
  }

  public func listScanRuns(
    request: ListScanRunsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ListScanRunsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listScanRuns(
    byItem: ListScanRunsRequest
  ) throws -> any AsyncSequence<ScanRun, Swift.Error> {
    try self.listScanRuns(byItem: byItem, options: .init())
  }

  public func listScanRuns(
    byItem: ListScanRunsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ScanRun, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWebSecurityScannerV1.ListScanRunsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func stopScanRun(request: StopScanRunRequest) async throws
    -> GoogleCloudWebSecurityScannerV1.ScanRun
  {
    try await self.stopScanRun(request: request, options: .init())
  }

  public func stopScanRun(
    request: StopScanRunRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ScanRun {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listCrawledUrls(request: ListCrawledUrlsRequest) async throws
    -> GoogleCloudWebSecurityScannerV1.ListCrawledUrlsResponse
  {
    try await self.listCrawledUrls(request: request, options: .init())
  }

  public func listCrawledUrls(
    request: ListCrawledUrlsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ListCrawledUrlsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listCrawledUrls(
    byItem: ListCrawledUrlsRequest
  ) throws -> any AsyncSequence<CrawledUrl, Swift.Error> {
    try self.listCrawledUrls(byItem: byItem, options: .init())
  }

  public func listCrawledUrls(
    byItem: ListCrawledUrlsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<CrawledUrl, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWebSecurityScannerV1.ListCrawledUrlsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getFinding(request: GetFindingRequest) async throws
    -> GoogleCloudWebSecurityScannerV1.Finding
  {
    try await self.getFinding(request: request, options: .init())
  }

  public func getFinding(
    request: GetFindingRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.Finding {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listFindings(request: ListFindingsRequest) async throws
    -> GoogleCloudWebSecurityScannerV1.ListFindingsResponse
  {
    try await self.listFindings(request: request, options: .init())
  }

  public func listFindings(
    request: ListFindingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listFindings(
    byItem: ListFindingsRequest
  ) throws -> any AsyncSequence<Finding, Swift.Error> {
    try self.listFindings(byItem: byItem, options: .init())
  }

  public func listFindings(
    byItem: ListFindingsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Finding, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listFindingTypeStats(request: ListFindingTypeStatsRequest) async throws
    -> GoogleCloudWebSecurityScannerV1.ListFindingTypeStatsResponse
  {
    try await self.listFindingTypeStats(request: request, options: .init())
  }

  public func listFindingTypeStats(
    request: ListFindingTypeStatsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudWebSecurityScannerV1.ListFindingTypeStatsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
