// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Information reported for an XSS.
public struct Xss: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Stack traces leading to the point where the XSS occurred.
  public var stackTraces: [Swift.String] = []

  /// An error message generated by a javascript breakage.
  public var errorMessage: Swift.String = Swift.String()

  /// The attack vector of the payload triggering this XSS.
  public var attackVector: Xss.AttackVector = Xss.AttackVector()

  /// The reproduction url for the seeding POST request of a Stored XSS.
  public var storedXssSeedingUrl: Swift.String = Swift.String()

  /// Initialize a new instance of `Xss`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Xss().with { $0.stackTraces = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Types of XSS attack vector.
  public enum AttackVector: Codable, Equatable, Sendable {
    /// Unknown attack vector.
    case unspecified
    /// The attack comes from fuzzing the browser's localStorage.
    case localStorage
    /// The attack comes from fuzzing the browser's sessionStorage.
    case sessionStorage
    /// The attack comes from fuzzing the window's name property.
    case windowName
    /// The attack comes from fuzzing the referrer property.
    case referrer
    /// The attack comes from fuzzing an input element.
    case formInput
    /// The attack comes from fuzzing the browser's cookies.
    case cookie
    /// The attack comes from hijacking the post messaging mechanism.
    case postMessage
    /// The attack comes from fuzzing parameters in the url.
    case getParameters
    /// The attack comes from fuzzing the fragment in the url.
    case urlFragment
    /// The attack comes from fuzzing the HTML comments.
    case htmlComment
    /// The attack comes from fuzzing the POST parameters.
    case postParameters
    /// The attack comes from fuzzing the protocol.
    case `protocol`
    /// The attack comes from the server side and is stored.
    case storedXss
    /// The attack is a Same-Origin Method Execution attack via a GET parameter.
    case sameOrigin
    /// The attack payload is received from a third-party host via a URL that is
    /// user-controllable
    case userControllableUrl
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .localStorage: return 1
      case .sessionStorage: return 2
      case .windowName: return 3
      case .referrer: return 4
      case .formInput: return 5
      case .cookie: return 6
      case .postMessage: return 7
      case .getParameters: return 8
      case .urlFragment: return 9
      case .htmlComment: return 10
      case .postParameters: return 11
      case .`protocol`: return 12
      case .storedXss: return 13
      case .sameOrigin: return 14
      case .userControllableUrl: return 15
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ATTACK_VECTOR_UNSPECIFIED"
      case .localStorage: return "LOCAL_STORAGE"
      case .sessionStorage: return "SESSION_STORAGE"
      case .windowName: return "WINDOW_NAME"
      case .referrer: return "REFERRER"
      case .formInput: return "FORM_INPUT"
      case .cookie: return "COOKIE"
      case .postMessage: return "POST_MESSAGE"
      case .getParameters: return "GET_PARAMETERS"
      case .urlFragment: return "URL_FRAGMENT"
      case .htmlComment: return "HTML_COMMENT"
      case .postParameters: return "POST_PARAMETERS"
      case .`protocol`: return "PROTOCOL"
      case .storedXss: return "STORED_XSS"
      case .sameOrigin: return "SAME_ORIGIN"
      case .userControllableUrl: return "USER_CONTROLLABLE_URL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AttackVector/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ATTACK_VECTOR_UNSPECIFIED": self = .unspecified
      case "LOCAL_STORAGE": self = .localStorage
      case "SESSION_STORAGE": self = .sessionStorage
      case "WINDOW_NAME": self = .windowName
      case "REFERRER": self = .referrer
      case "FORM_INPUT": self = .formInput
      case "COOKIE": self = .cookie
      case "POST_MESSAGE": self = .postMessage
      case "GET_PARAMETERS": self = .getParameters
      case "URL_FRAGMENT": self = .urlFragment
      case "HTML_COMMENT": self = .htmlComment
      case "POST_PARAMETERS": self = .postParameters
      case "PROTOCOL": self = .`protocol`
      case "STORED_XSS": self = .storedXss
      case "SAME_ORIGIN": self = .sameOrigin
      case "USER_CONTROLLABLE_URL": self = .userControllableUrl
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AttackVector/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .localStorage
      case 2: self = .sessionStorage
      case 3: self = .windowName
      case 4: self = .referrer
      case 5: self = .formInput
      case 6: self = .cookie
      case 7: self = .postMessage
      case 8: self = .getParameters
      case 9: self = .urlFragment
      case 10: self = .htmlComment
      case 11: self = .postParameters
      case 12: self = .`protocol`
      case 13: self = .storedXss
      case 14: self = .sameOrigin
      case 15: self = .userControllableUrl
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .localStorage: return try container.encode(1)
      case .sessionStorage: return try container.encode(2)
      case .windowName: return try container.encode(3)
      case .referrer: return try container.encode(4)
      case .formInput: return try container.encode(5)
      case .cookie: return try container.encode(6)
      case .postMessage: return try container.encode(7)
      case .getParameters: return try container.encode(8)
      case .urlFragment: return try container.encode(9)
      case .htmlComment: return try container.encode(10)
      case .postParameters: return try container.encode(11)
      case .`protocol`: return try container.encode(12)
      case .storedXss: return try container.encode(13)
      case .sameOrigin: return try container.encode(14)
      case .userControllableUrl: return try container.encode(15)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.websecurityscanner.v1.Xss"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
